import 'package:stacked/stacked.dart';

import 'dummy_model.dart';

class EmployeeViewModel extends BaseViewModel {
  List<DummyData> items = [
    DummyData(
        'assets/pulse.png',
        'ALi Hassan',
        'male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
    DummyData('assets/pulse.png', 'Kashif', 'male', 'Monday, 25 October 2021',
        'Dummy Text', 'Dummy Text1', 'Dummy Text2', 'Dummy Text3'),
    DummyData('assets/pulse.png', 'Salman', 'male', 'Monday, 25 October 2021',
        'Dummy Text', 'Dummy Text1', 'Dummy Text2', 'Dummy Text3'),
    DummyData('assets/pulse.png', 'Hamza', 'male', 'Monday, 25 October 2021',
        'Dummy Text', 'Dummy Text1', 'Dummy Text2', 'Dummy Text3'),
    DummyData(
        'assets/pulse.png',
        'Shah Zaman',
        'male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
    DummyData('assets/pulse.png', 'Farid', 'male', 'Monday, 25 October 2021',
        'Dummy Text', 'Dummy Text1', 'Dummy Text2', 'Dummy Text3'),
    DummyData(
        'assets/pulse.png',
        'ALi Hassan',
        'male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
    DummyData(
        'assets/pulse.png',
        'ALi Hassan',
        'Male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
    DummyData(
        'assets/pulse.png',
        'ALi Hassan',
        'male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
    DummyData(
        'assets/pulse.png',
        'ALi Hassan',
        'male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
    DummyData(
        'assets/pulse.png',
        'ALi Hassan',
        'male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
    DummyData(
        'assets/pulse.png',
        'ALi Hassan',
        'male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
    DummyData(
        'assets/pulse.png',
        'ALi Hassan',
        'male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
    DummyData(
        'assets/pulse.png',
        'ALi Hassan',
        'male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
    DummyData(
        'assets/pulse.png',
        'ALi Hassan',
        'Male',
        'Monday, 25 October 2021',
        'Dummy Text',
        'Dummy Text1',
        'Dummy Text2',
        'Dummy Text3'),
  ];
}
